import Link from 'next/link';
import { getCurrentUser } from '../../lib/auth/session.js';
import { listUserOrders } from '../../server/orders/service.js';

export const metadata = { title: 'سفارش‌های من' };
const money = (value) => new Intl.NumberFormat('fa-IR').format(Number(value || 0));
const status = { PENDING: 'در انتظار پرداخت', PAID: 'پرداخت شده', PROCESSING: 'در حال پردازش', SHIPPED: 'ارسال شده', DELIVERED: 'تحویل شده', CANCELLED: 'لغو شده', REFUNDED: 'مرجوع شده' };
const payment = { UNPAID: 'پرداخت نشده', PAID: 'پرداخت شده', FAILED: 'ناموفق', REFUNDED: 'بازپرداخت شده' };
const tone = { PENDING: 'bg-amber-50 text-amber-700', PAID: 'bg-emerald-50 text-emerald-700', PROCESSING: 'bg-blue-50 text-blue-700', SHIPPED: 'bg-violet-50 text-violet-700', DELIVERED: 'bg-emerald-50 text-emerald-700', CANCELLED: 'bg-slate-100 text-slate-500', REFUNDED: 'bg-red-50 text-red-700' };

export default async function OrdersPage({ searchParams }) {
  const user = await getCurrentUser();
  if (!user) return <div className="store-shell py-24"><div className="mx-auto max-w-lg rounded-[28px] border border-[var(--border)] bg-white px-6 py-14 text-center shadow-[0_18px_55px_rgba(23,23,23,.045)]"><h1 className="text-2xl font-black">سفارش‌های شما</h1><p className="mt-3 text-[11px] leading-7 text-slate-500">برای مشاهده تاریخچه خریدها وارد حساب کاربری خود شوید.</p><Link href="/login?returnTo=/orders" className="mt-6 inline-flex rounded-[12px] bg-[var(--brand)] px-7 py-3 text-[11px] font-black text-white">ورود به حساب</Link></div></div>;
  const params = await searchParams;
  const result = await listUserOrders(user.id, { page: Math.max(Number(params.page) || 1, 1), limit: 20 });
  return <main dir="rtl" className="store-shell py-7 sm:py-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-black text-[var(--brand)]">تاریخچه خرید</p><h1 className="mt-2 text-3xl font-black tracking-tight">سفارش‌های من</h1><p className="mt-2 text-[11px] text-slate-400">تمام سفارش‌های ثبت‌شده برای حساب شما</p></div><Link href="/products" className="inline-flex w-fit rounded-[11px] border border-[var(--border)] bg-white px-4 py-2.5 text-[10px] font-black hover:border-slate-300">ادامه خرید</Link></div>{!result.orders.length ? <div className="mt-8 rounded-[28px] border border-dashed border-[var(--border)] bg-white px-6 py-16 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-[#fafaf8] text-xl">⌁</div><h2 className="mt-5 text-lg font-black">هنوز سفارشی ثبت نکرده‌اید</h2><p className="mt-2 text-[10px] text-slate-400">اولین خریدتان را از میان محصولات شروع کنید.</p><Link href="/products" className="mt-5 inline-flex rounded-[11px] bg-slate-950 px-6 py-3 text-[10px] font-black text-white hover:bg-[var(--brand)]">مشاهده محصولات</Link></div> : <div className="mt-8 grid gap-4">{result.orders.map((order) => <Link key={order.id} href={`/orders/${order.id}`} className="group rounded-[24px] border border-[var(--border)] bg-white p-5 shadow-[0_10px_30px_rgba(23,23,23,.025)] transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-[0_18px_45px_rgba(23,23,23,.06)]"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-[13px] bg-[#fafaf8] text-sm">▤</div><div className="min-w-0 flex-1"><div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-bold text-slate-400">شماره سفارش</p><p className="mt-1 font-mono text-[11px] font-black">{order.orderNumber}</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1.5 text-[9px] font-black ${tone[order.status] || 'bg-slate-100 text-slate-500'}`}>{status[order.status] || order.status}</span><span className="rounded-full bg-slate-50 px-3 py-1.5 text-[9px] font-bold text-slate-400">{payment[order.paymentStatus] || order.paymentStatus}</span></div></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[var(--border)] pt-4"><div><span className="text-[9px] text-slate-400">مبلغ نهایی</span><strong className="mr-2 text-[12px]">{money(order.totalAmount)} تومان</strong></div><span className="text-[10px] font-black text-slate-300 transition group-hover:text-[var(--brand)]">مشاهده جزئیات ←</span></div></div></div></Link>)}</div>}{result.pagination.hasMore && <div className="mt-7 text-center"><Link href={`/orders?page=${Number(result.pagination.page) + 1}`} className="inline-flex rounded-[11px] border border-[var(--border)] bg-white px-5 py-3 text-[10px] font-black">سفارش‌های قدیمی‌تر</Link></div>}</main>;
}
