import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser } from '../../../lib/auth/session.js';
import { getUserOrder } from '../../../server/orders/service.js';

const money = (value) => new Intl.NumberFormat('fa-IR').format(Number(value || 0));
const status = { PENDING: 'در انتظار پرداخت', PAID: 'پرداخت شده', PROCESSING: 'در حال پردازش', SHIPPED: 'ارسال شده', DELIVERED: 'تحویل شده', CANCELLED: 'لغو شده', REFUNDED: 'مرجوع شده' };
const payment = { UNPAID: 'پرداخت نشده', PAID: 'پرداخت شده', FAILED: 'پرداخت ناموفق', REFUNDED: 'بازپرداخت شده' };
const tone = { PENDING: 'bg-amber-50 text-amber-700', PAID: 'bg-emerald-50 text-emerald-700', PROCESSING: 'bg-blue-50 text-blue-700', SHIPPED: 'bg-violet-50 text-violet-700', DELIVERED: 'bg-emerald-50 text-emerald-700', CANCELLED: 'bg-slate-100 text-slate-500', REFUNDED: 'bg-red-50 text-red-700' };
const steps = ['PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED'];
const stepLabels = { PAID: 'پرداخت', PROCESSING: 'پردازش', SHIPPED: 'ارسال', DELIVERED: 'تحویل' };

export async function generateMetadata({ params }) { try { const user = await requireUser(); const order = await getUserOrder(user.id, Number((await params).id)); return { title: order ? `سفارش ${order.orderNumber}` : 'سفارش پیدا نشد' }; } catch { return { title: 'سفارش' }; } }

export default async function OrderDetailPage({ params, searchParams }) {
  const { id } = await params; const query = await searchParams; let order;
  try { const user = await requireUser(); order = await getUserOrder(user.id, Number(id)); } catch { return <div className="store-shell py-24"><div className="mx-auto max-w-lg rounded-[22px] border border-[var(--border)] bg-white px-6 py-14 text-center"><h1 className="text-2xl font-black">برای مشاهده سفارش وارد شوید</h1><Link href={`/login?returnTo=/orders/${encodeURIComponent(id)}`} className="mt-6 inline-flex rounded-[11px] bg-[var(--brand)] px-6 py-3 text-[10px] font-black text-white">ورود به حساب</Link></div></div>; }
  if (!order) notFound();
  const paymentResult = query?.payment; const showSuccess = paymentResult === 'success' && order.paymentStatus === 'PAID'; const showFailure = paymentResult === 'failed'; const showUnavailable = paymentResult === 'unavailable'; const canRetry = order.status === 'PENDING' && order.paymentStatus !== 'PAID';
  const currentStep = steps.indexOf(order.status); const isCancelled = ['CANCELLED', 'REFUNDED'].includes(order.status);
  return <main dir="rtl" className="store-shell py-7 sm:py-10"><Link href="/orders" className="text-[10px] font-black text-slate-400 transition hover:text-[var(--brand)]">← بازگشت به سفارش‌ها</Link>
    {showSuccess && <Notice type="success" title="پرداخت با موفقیت تأیید شد." text="سفارش شما با موفقیت ثبت شده و در حال پردازش است."/>}{showUnavailable && <Notice type="warning" title="سفارش شما با موفقیت ثبت شد." text="پرداخت آنلاین در حال حاضر فعال نیست. سفارش در وضعیت «در انتظار پرداخت» باقی می‌ماند."/>}{showFailure && <Notice type="error" title="پرداخت انجام نشد." text="وضعیت پرداخت سفارش را بررسی کنید و در صورت امکان دوباره تلاش کنید."/>}{isCancelled && <Notice type="warning" title={order.status === 'REFUNDED' ? 'این سفارش بازپرداخت شده است.' : 'این سفارش لغو شده است.'} text="وضعیت نهایی سفارش در اطلاعات زیر نمایش داده شده است."/>}
    <header className="mt-5 border border-[var(--border)] bg-white p-6 shadow-[0_12px_38px_rgba(23,23,23,.035)] sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[9px] font-bold text-slate-400">شماره سفارش</p><h1 className="mt-1 font-mono text-xl font-black">{order.orderNumber}</h1><p className="mt-2 text-[9px] text-slate-400">جزئیات سفارش و وضعیت ارسال</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1.5 text-[9px] font-black ${tone[order.status] || 'bg-slate-100 text-slate-500'}`}>{status[order.status] || order.status}</span><span className="rounded-full bg-slate-50 px-3 py-1.5 text-[9px] font-bold text-slate-400">{payment[order.paymentStatus] || order.paymentStatus}</span></div></div></header>
    {!isCancelled && <section className="mt-5 border border-[var(--border)] bg-white p-6 shadow-[0_10px_30px_rgba(23,23,23,.025)] sm:p-7"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black text-[var(--brand)]">پیگیری سفارش</p><h2 className="mt-1 text-base font-black">وضعیت سفارش</h2></div><span className="text-[9px] font-bold text-slate-400">{status[order.status] || order.status}</span></div><div className="mt-7 grid grid-cols-4 gap-1">{steps.map((step, index) => { const done = currentStep >= index; const active = currentStep === index; return <div key={step} className="relative text-center"><div className={`mx-auto grid h-9 w-9 place-items-center rounded-full text-[10px] font-black transition ${done ? 'bg-[var(--brand)] text-white' : 'bg-slate-100 text-slate-400'} ${active ? 'ring-4 ring-red-50' : ''}`}>{done ? '✓' : index + 1}</div><p className={`mt-2 text-[8px] font-black sm:text-[9px] ${done ? 'text-slate-800' : 'text-slate-400'}`}>{stepLabels[step]}</p>{index < steps.length - 1 && <div className={`absolute left-1/2 top-4 hidden h-px w-full -translate-y-1/2 sm:block ${currentStep > index ? 'bg-[var(--brand)]' : 'bg-slate-200'}`} aria-hidden="true"/>}</div>; })}</div></section>}
    {canRetry && <div className="mt-5 flex flex-col gap-4 border border-amber-200 bg-amber-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[11px] font-black text-amber-900">پرداخت این سفارش هنوز تکمیل نشده است.</p><p className="mt-1 text-[10px] leading-6 text-amber-700">درگاه آنلاین فعلاً فعال نیست؛ پس از فعال شدن می‌توانید پرداخت را ادامه دهید.</p></div><Link href={`/checkout?orderId=${encodeURIComponent(order.id)}`} className="inline-flex w-fit rounded-[11px] bg-[var(--brand)] px-5 py-2.5 text-[10px] font-black text-white">ادامه پرداخت</Link></div>}
    <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_330px]"><section className="border border-[var(--border)] bg-white p-6 shadow-[0_10px_30px_rgba(23,23,23,.025)]"><div className="flex items-center justify-between"><h2 className="text-lg font-black">اقلام سفارش</h2><span className="text-[9px] font-bold text-slate-400">{order.items.length.toLocaleString('fa-IR')} قلم</span></div><div className="mt-5 divide-y divide-[var(--border)]">{order.items.map((item) => <div key={item.id} className="flex gap-4 py-5 first:pt-0 last:pb-0">{item.productSlug ? <Link href={`/products/${encodeURIComponent(item.productSlug)}`} className="relative h-14 w-14 shrink-0 overflow-hidden bg-[#fafaf8] transition hover:opacity-80" aria-label={`مشاهده ${item.productName}`}>{item.imageUrl ? <Image src={item.imageUrl} alt={item.productName} fill sizes="56px" className="object-contain"/> : <span className="flex h-full items-center justify-center text-xs text-slate-300">—</span>}</Link> : <div className="relative h-14 w-14 shrink-0 overflow-hidden bg-[#fafaf8]">{item.imageUrl ? <Image src={item.imageUrl} alt={item.productName} fill sizes="56px" className="object-contain"/> : <span className="flex h-full items-center justify-center text-xs text-slate-300">—</span>}</div>}<div className="min-w-0 flex-1">{item.productSlug ? <Link href={`/products/${encodeURIComponent(item.productSlug)}`} className="text-[11px] font-black transition hover:text-[var(--brand)]">{item.productName}</Link> : <p className="text-[11px] font-black">{item.productName}</p>}<p className="mt-1 text-[9px] text-slate-400">{item.sku} · تعداد {money(item.quantity)}</p></div><p className="shrink-0 text-[10px] font-black">{money(item.lineTotal)} تومان</p></div>)}</div></section><aside className="h-fit space-y-5 lg:sticky lg:top-24"><div className="border border-[var(--border)] bg-white p-6"><h2 className="text-base font-black">خلاصه مالی</h2><div className="mt-5 space-y-3 text-[10px]"><Row label="جمع کالاها" value={`${money(order.subtotal)} تومان`}/><Row label="تخفیف" value={`− ${money(order.discountAmount)} تومان`} green/><Row label="ارسال" value={`${money(order.shippingAmount)} تومان`}/><div className="flex justify-between border-t border-[var(--border)] pt-5 text-[12px] font-black"><span>مبلغ نهایی</span><span>{money(order.totalAmount)} تومان</span></div></div></div><div className="border border-[var(--border)] bg-white p-6"><h2 className="text-base font-black">آدرس ارسال</h2><p className="mt-4 text-[10px] font-black">{order.shippingAddress.recipientName}</p><p className="mt-2 text-[9px] leading-6 text-slate-500">{order.shippingAddress.province}، {order.shippingAddress.city}<br/>{order.shippingAddress.addressLine}<br/>{order.shippingAddress.postalCode} · {order.shippingAddress.recipientPhone}</p></div></aside></div>
  </main>;
}
function Row({ label, value, green }) { return <div className={`flex justify-between ${green ? 'text-emerald-700' : ''}`}><span className="text-slate-500">{label}</span><span className="font-bold">{value}</span></div>; }
function Notice({ type, title, text }) { const classes = { success: 'border-emerald-200 bg-emerald-50 text-emerald-800', warning: 'border-amber-200 bg-amber-50 text-amber-800', error: 'border-red-200 bg-red-50 text-red-800' }; return <div role={type === 'error' ? 'alert' : 'status'} className={`mt-5 border p-5 ${classes[type]}`}><p className="text-[11px] font-black">{title}</p><p className="mt-1 text-[10px] leading-6 opacity-80">{text}</p></div>; }
