import Link from 'next/link';
import { listAdminProducts } from '../../../server/admin/products.js';

export default async function AdminProductsPage({ searchParams }) {
  const params = await searchParams;
  const search = params?.search?.trim() || null;
  const products = await listAdminProducts({ search, limit: 100, offset: 0 });
  return <section dir="rtl"><div className="mb-6 flex items-end justify-between gap-4"><div><p className="text-sm font-semibold text-slate-500">کاتالوگ</p><h1 className="mt-1 text-3xl font-black">محصولات</h1></div><Link href="/products" className="rounded-xl border bg-white px-4 py-2 text-sm font-bold">مشاهده فروشگاه</Link></div><form className="mb-5 flex gap-2" method="get"><input name="search" defaultValue={search ?? ''} placeholder="جستجوی نام، اسلاگ یا SKU" className="min-w-0 flex-1 rounded-xl border bg-white px-4 py-3 outline-none focus:ring-2" /><button className="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">جستجو</button></form><div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><table className="w-full min-w-[800px] text-right text-sm"><thead className="border-b bg-slate-50"><tr><th className="p-4">محصول</th><th className="p-4">وضعیت</th><th className="p-4">تنوع‌ها</th><th className="p-4">موجودی قابل فروش</th><th className="p-4">شناسه</th></tr></thead><tbody className="divide-y">{products.map((product) => <tr key={product.id}><td className="p-4"><div className="font-extrabold">{product.name}</div><div className="mt-1 text-xs text-slate-400">{product.slug}</div></td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${product.is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{product.is_active ? 'فعال' : 'غیرفعال'}</span></td><td className="p-4">{product.variant_count}</td><td className="p-4 font-bold">{product.available_units}</td><td className="p-4 font-mono text-xs">{product.id}</td></tr>)}</tbody></table>{products.length === 0 && <div className="p-10 text-center text-slate-500">محصولی پیدا نشد.</div>}</div></section>;
}
