import Image from 'next/image';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { requireUser } from '../../lib/auth/session.js';
import { getProfile, listAddresses } from '../../server/account/service.js';
import { query } from '../../server/db/connection.js';

const money = (value) => new Intl.NumberFormat('fa-IR').format(Number(value || 0));
const orderStatus = { PENDING: 'در انتظار پرداخت', PAID: 'پرداخت شده', PROCESSING: 'در حال پردازش', SHIPPED: 'ارسال شده', DELIVERED: 'تحویل شده', CANCELLED: 'لغو شده', REFUNDED: 'مرجوع شده' };
const statusTone = { PENDING: 'bg-amber-50 text-amber-700', PAID: 'bg-emerald-50 text-emerald-700', PROCESSING: 'bg-blue-50 text-blue-700', SHIPPED: 'bg-violet-50 text-violet-700', DELIVERED: 'bg-emerald-50 text-emerald-700', CANCELLED: 'bg-red-50 text-red-700', REFUNDED: 'bg-slate-100 text-slate-600' };

export default async function AccountPage() {
  let user;
  try { user = await requireUser(); } catch (error) { if (error?.code === 'UNAUTHENTICATED') redirect('/login?next=/account'); throw error; }
  const [profile, addresses, orders, favorites] = await Promise.all([getProfile(user.id), listAddresses(user.id), query(`SELECT id,order_number,status,payment_status,total_amount,created_at FROM orders WHERE user_id=? ORDER BY created_at DESC,id DESC LIMIT 6`, [user.id]), query(`SELECT f.product_id,p.name,p.slug,(SELECT pi.url FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.is_primary DESC,pi.sort_order ASC,pi.id ASC LIMIT 1) AS thumbnail_url FROM favorites f INNER JOIN products p ON p.id=f.product_id AND p.deleted_at IS NULL WHERE f.user_id=? ORDER BY f.created_at DESC LIMIT 4`, [user.id])]);
  return <main dir="rtl" className="store-shell py-7 sm:py-10">
    <header className="relative overflow-hidden border border-[var(--border)] bg-[#fafaf8] px-5 py-8 sm:px-8 sm:py-10"><div className="absolute -left-16 -top-20 h-48 w-48 rounded-full bg-[var(--brand)]/[0.045] blur-3xl"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black text-[var(--brand)]"><span className="h-1.5 w-1.5 rounded-full bg-[var(--brand)]"/>فضای شخصی شما</div><h1 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">سلام {profile?.firstName || 'دوست عزیز'} 👋</h1><p className="mt-2 max-w-2xl text-[11px] leading-7 text-slate-500">سفارش‌ها، علاقه‌مندی‌ها، اطلاعات شخصی و آدرس‌های خود را از یکجا مدیریت کنید.</p></div><div className="flex flex-wrap gap-2"><Link href="/orders" className="inline-flex items-center gap-2 rounded-[11px] bg-[var(--brand)] px-4 py-2.5 text-[10px] font-black text-white shadow-[0_8px_20px_rgba(220,38,38,.14)] transition hover:-translate-y-0.5 hover:shadow-[0_10px_24px_rgba(220,38,38,.2)]">سفارش‌های من <span>←</span></Link><Link href="/account/profile" className="inline-flex items-center rounded-[11px] border border-[var(--border)] bg-white px-4 py-2.5 text-[10px] font-black transition hover:border-slate-300 hover:bg-white">ویرایش پروفایل</Link></div></div></header>
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><Stat value={orders.length} label="سفارش اخیر" hint="آخرین فعالیت‌ها"/><Stat value={addresses.length} label="آدرس ثبت‌شده" hint="مقصدهای شما"/><Stat value={favorites.length} label="علاقه‌مندی" hint="محصولات ذخیره‌شده"/></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1.15fr_.85fr]"><section className="rounded-[18px] border border-[var(--border)] bg-white p-5 shadow-[0_10px_30px_rgba(23,23,23,.025)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black text-[var(--brand)]">آخرین فعالیت</p><h2 className="mt-1 text-lg font-black">سفارش‌های اخیر</h2></div><Link href="/orders" className="text-[10px] font-black text-slate-400 transition hover:text-[var(--brand)]">مشاهده همه ←</Link></div><div className="mt-5 divide-y divide-[var(--border)]">{orders.map((o) => <Link href={`/orders/${o.id}`} key={o.id} className="group flex items-center gap-3 py-4 first:pt-0 last:pb-0 sm:gap-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-[12px] ${statusTone[o.status] || 'bg-slate-100 text-slate-500'}`}><span className="text-[13px] font-black">{o.status === 'DELIVERED' ? '✓' : o.status === 'CANCELLED' ? '×' : '◷'}</span></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-mono text-[10px] font-black">{o.order_number}</p><span className={`rounded-full px-2 py-1 text-[8px] font-black ${statusTone[o.status] || 'bg-slate-100 text-slate-500'}`}>{orderStatus[o.status] || o.status}</span></div><p className="mt-1 text-[9px] text-slate-400">جزئیات سفارش و وضعیت ارسال</p></div><strong className="hidden shrink-0 text-[10px] sm:block">{money(o.total_amount)} تومان</strong><span className="text-[11px] text-slate-300 transition group-hover:-translate-x-0.5 group-hover:text-[var(--brand)]">←</span></Link>)}{!orders.length && <Empty label="شروع خرید" href="/products"/>}</div></section><section className="rounded-[18px] border border-[var(--border)] bg-white p-5 shadow-[0_10px_30px_rgba(23,23,23,.025)] sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black text-[var(--brand)]">اطلاعات حساب</p><h2 className="mt-1 text-lg font-black">مشخصات شخصی</h2></div><Link href="/account/profile" className="text-[10px] font-black text-slate-400 transition hover:text-[var(--brand)]">ویرایش</Link></div><div className="mt-5 grid gap-2 text-[10px] sm:grid-cols-2"><Info label="نام" value={[profile?.firstName, profile?.lastName].filter(Boolean).join(' ') || 'ثبت نشده'}/><Info label="ایمیل" value={profile?.email || '—'}/><Info label="تلفن" value={profile?.phone || '—'}/><Info label="آدرس‌ها" value={`${addresses.length.toLocaleString('fa-IR')} آدرس`}/></div></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-[18px] border border-[var(--border)] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black text-[var(--brand)]">محصولات ذخیره‌شده</p><h2 className="mt-1 text-lg font-black">علاقه‌مندی‌ها</h2></div><Link href="/favorites" className="text-[10px] font-black text-slate-400 transition hover:text-[var(--brand)]">مشاهده همه ←</Link></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{favorites.map((f) => <Link href={`/products/${f.slug}`} key={f.product_id} className="group overflow-hidden rounded-[13px] border border-transparent bg-[#fafaf8] p-2.5 transition hover:border-[var(--border)] hover:bg-white"><div className="relative aspect-square overflow-hidden rounded-[10px] bg-white">{f.thumbnail_url ? <Image src={f.thumbnail_url} alt={f.name} fill sizes="(min-width: 640px) 120px, 42vw" className="object-contain transition duration-300 group-hover:scale-[1.04]"/> : <span className="flex h-full items-center justify-center text-[9px] text-slate-400">تصویر ندارد</span>}</div><p className="mt-2 line-clamp-2 text-[9px] font-black leading-5">{f.name}</p></Link>)}{!favorites.length && <p className="col-span-full bg-[#fafaf8] p-6 text-center text-[10px] text-slate-400">هنوز محصولی به علاقه‌مندی‌ها اضافه نکرده‌اید.</p>}</div></section><section className="rounded-[18px] border border-[var(--border)] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black text-[var(--brand)]">مقصدهای ارسال</p><h2 className="mt-1 text-lg font-black">آدرس‌های من</h2></div><Link href="/account/addresses" className="text-[10px] font-black text-slate-400 transition hover:text-[var(--brand)]">مدیریت آدرس‌ها ←</Link></div><div className="mt-5 grid gap-2">{addresses.slice(0,3).map((a) => <div key={a.id} className="rounded-[12px] border border-transparent bg-[#fafaf8] p-4 transition hover:border-[var(--border)]"><div className="flex justify-between gap-3"><b className="text-[10px]">{a.recipient_name}</b>{a.is_default ? <span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-black text-emerald-600">پیش‌فرض</span> : null}</div><p className="mt-2 text-[10px] leading-6 text-slate-500">{a.province}، {a.city}<br/>{a.address_line}</p></div>)}{!addresses.length && <p className="bg-[#fafaf8] p-6 text-center text-[10px] text-slate-400">هنوز آدرسی ثبت نکرده‌اید.</p>}</div></section></div>
  </main>;
}
function Stat({ value, label, hint }) { return <div className="group rounded-[18px] border border-[var(--border)] bg-white p-5 shadow-[0_8px_24px_rgba(23,23,23,.02)] transition hover:-translate-y-0.5 hover:shadow-[0_12px_28px_rgba(23,23,23,.05)]"><div className="flex items-start justify-between gap-3"><div><p className="text-2xl font-black tracking-tight">{Number(value).toLocaleString('fa-IR')}</p><p className="mt-1 text-[9px] font-black text-slate-500">{label}</p><p className="mt-1 text-[8px] text-slate-400">{hint}</p></div><span className="mt-1 h-2 w-2 rounded-full bg-[var(--brand)] opacity-60 transition group-hover:scale-125"/></div></div>; }
function Info({ label, value }) { return <div className="rounded-[12px] bg-[#fafaf8] p-4 transition hover:bg-[#f7f7f3]"><span className="text-[9px] text-slate-400">{label}</span><p className="mt-1 truncate text-[10px] font-black text-slate-800">{value}</p></div>; }
function Empty({ href, label }) { return <div className="py-10 text-center text-[10px] text-slate-400"><p>هنوز سفارشی ندارید.</p><Link href={href} className="mt-4 inline-flex rounded-[10px] bg-slate-950 px-4 py-2 text-white transition hover:bg-[var(--brand)]">{label}</Link></div>; }
