/* eslint-disable @next/next/no-img-element */
import Link from 'next/link';
import ProductCard from './ProductCard';

function getItems(payload, key) { return payload?.ok && Array.isArray(payload.data?.[key]) ? payload.data[key] : []; }
async function getJson(path) { try { const base = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'; const response = await fetch(`${base}${path}`, { next: { revalidate: 60 } }); return response.ok ? response.json() : null; } catch { return null; } }

export default async function HomeSections() {
  const [productsPayload, categoriesPayload] = await Promise.all([getJson('/api/products?limit=8&sort=created_at&direction=desc'), getJson('/api/categories?limit=8')]);
  const products = getItems(productsPayload, 'products'); const categories = getItems(categoriesPayload, 'categories'); const hero = products.find((p) => p.primary_image_url || p.image_url);
  return <div className="pb-16">
    <section className="store-shell pt-5 sm:pt-7"><div className="relative grid min-h-[500px] overflow-hidden border border-[var(--border)] bg-[#f0ede6] lg:grid-cols-[1.05fr_.95fr]">
      <div className="relative z-10 flex items-center px-6 py-12 sm:px-10 lg:px-14"><div className="max-w-[620px]"><p className="text-[10px] font-black tracking-wide text-[var(--brand)]">فروشگاه آنلاین شما</p><h1 className="mt-5 text-[43px] font-black leading-[1.2] tracking-[-.06em] text-[#151515] sm:text-6xl lg:text-[66px]">انتخاب خوب،<br/><span className="text-[var(--brand)]">ساده‌تر از همیشه.</span></h1><p className="mt-6 max-w-[520px] text-[13px] font-medium leading-8 text-[#62605b] sm:text-[14px]">محصولات منتخب، قیمت‌های شفاف و تجربه‌ای سریع و آرام برای خرید روزمره شما.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="inline-flex h-12 items-center bg-[#171717] px-7 text-[12px] font-black text-white transition hover:bg-[var(--brand)]">مشاهده محصولات</Link><Link href="/categories" className="inline-flex h-12 items-center border border-[#d1ccc1] bg-white/70 px-7 text-[12px] font-black text-[#292929] transition hover:bg-white">دسته‌بندی‌ها</Link></div><div className="mt-10 flex flex-wrap gap-7 border-t border-[#d7d1c5] pt-5 text-[9px] font-bold text-slate-500"><span><b className="text-slate-900">سریع</b> · تجربه سبک</span><span><b className="text-slate-900">شفاف</b> · قیمت و ارسال</span><span><b className="text-slate-900">مطمئن</b> · پیگیری سفارش</span></div></div></div>
      <div className="relative min-h-[300px] overflow-hidden bg-[#e8e3d8] lg:min-h-0">{hero ? <><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_45%,rgba(255,255,255,.9),transparent_58%)]"/><img src={hero.primary_image_url || hero.image_url} alt={hero.name} className="absolute inset-0 h-full w-full object-contain p-8 sm:p-14 lg:p-16 transition duration-700 hover:scale-[1.025]"/></> : <div className="grid h-full place-items-center text-sm font-black text-slate-400">محصولات تازه به‌زودی</div>}</div>
    </div></section>
    {categories.length > 0 && <section className="store-shell pt-14 sm:pt-16"><div className="flex items-end justify-between border-b border-[var(--border)] pb-4"><div><p className="text-[9px] font-black text-[var(--brand)]">انتخاب سریع</p><h2 className="mt-1 text-xl font-black sm:text-2xl">دسته‌بندی‌های محبوب</h2></div><Link href="/categories" className="text-[10px] font-extrabold text-slate-400 hover:text-[var(--brand)]">مشاهده همه ←</Link></div><div className="mt-5 grid grid-cols-2 gap-x-3 gap-y-0 sm:grid-cols-4 lg:grid-cols-8">{categories.map((category) => <Link key={category.id} href={`/categories/${category.slug}`} className="group border-b border-[var(--border)] px-3 py-5 text-center transition hover:bg-white"><div className="mx-auto grid h-14 w-14 overflow-hidden bg-[var(--surface-soft)] text-sm font-black text-slate-500 transition group-hover:bg-[var(--brand-soft)] group-hover:text-[var(--brand)]">{category.image_url ? <img src={category.image_url} alt="" loading="lazy" className="h-full w-full object-cover transition duration-300 group-hover:scale-105"/> : <span className="grid h-full w-full place-items-center">{category.name?.slice(0,1)}</span>}</div><p className="mt-3 line-clamp-2 text-[10px] font-extrabold leading-5 text-slate-700">{category.name}</p></Link>)}</div></section>}
    {products.length > 0 && <section className="store-shell pt-14 sm:pt-16"><div className="flex items-end justify-between border-b border-[var(--border)] pb-4"><div><p className="text-[9px] font-black text-[var(--brand)]">تازه وارد شده</p><h2 className="mt-1 text-xl font-black sm:text-2xl">محصولات جدید</h2></div><Link href="/products" className="text-[10px] font-extrabold text-slate-400 hover:text-[var(--brand)]">مشاهده همه ←</Link></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 sm:gap-4 lg:grid-cols-4">{products.map((product) => <ProductCard key={product.id} product={product}/>)}</div></section>}
    <section className="store-shell pt-14 sm:pt-16"><div className="grid border-y border-[var(--border)] bg-white sm:grid-cols-3">{[['ارسال شفاف','روش و هزینه ارسال را قبل از پرداخت می‌بینی.'],['پرداخت امن','وضعیت سفارش و پرداخت را ساده پیگیری می‌کنی.'],['پشتیبانی','حساب، آدرس‌ها و خریدها همیشه در دسترس هستند.']].map(([title,text],i)=><div key={title} className={`px-6 py-7 ${i<2?'border-b border-[var(--border)] sm:border-b-0 sm:border-l':''}`}><p className="text-[12px] font-black">{title}</p><p className="mt-2 text-[10px] font-medium leading-6 text-slate-500">{text}</p></div>)}</div></section>
  </div>;
}
